name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Latest Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version: 'node'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd anyone-can-kitchen-dashboard
          npm ci

      - name: Build Project
        run: |
          cd anyone-can-kitchen-dashboard
          npm run build --if-present

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: anyone-can-kitchen-dashboard

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: anyone-can-kitchen-dashboard

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: anyone-can-kitchen-dashboard
